version: "2"
services:
  fill:
    build: ./fillDB
    depends_on:
      - db
    ports:
      - "8000:8000"
  read:
    build: ./readDB
    depends_on:
      - db
      - fill
    ports:
      - "5000:5000"
  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
